// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Unifi
{
    /// <summary>
    /// `unifi.RadiusProfile` manages RADIUS profiles.
    /// </summary>
    [UnifiResourceType("unifi:index/radiusProfile:RadiusProfile")]
    public partial class RadiusProfile : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Specifies whether to use RADIUS accounting. Defaults to `false`.
        /// </summary>
        [Output("accountingEnabled")]
        public Output<bool?> AccountingEnabled { get; private set; } = null!;

        /// <summary>
        /// RADIUS accounting servers.
        /// </summary>
        [Output("acctServers")]
        public Output<ImmutableArray<Outputs.RadiusProfileAcctServer>> AcctServers { get; private set; } = null!;

        /// <summary>
        /// RADIUS authentication servers.
        /// </summary>
        [Output("authServers")]
        public Output<ImmutableArray<Outputs.RadiusProfileAuthServer>> AuthServers { get; private set; } = null!;

        /// <summary>
        /// Specifies whether to use interim_update. Defaults to `false`.
        /// </summary>
        [Output("interimUpdateEnabled")]
        public Output<bool?> InterimUpdateEnabled { get; private set; } = null!;

        /// <summary>
        /// Specifies interim_update interval. Defaults to `3600`.
        /// </summary>
        [Output("interimUpdateInterval")]
        public Output<int?> InterimUpdateInterval { get; private set; } = null!;

        /// <summary>
        /// The name of the profile.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The name of the site to associate the settings with.
        /// </summary>
        [Output("site")]
        public Output<string> Site { get; private set; } = null!;

        /// <summary>
        /// Specifies whether to use usg as a RADIUS accounting server. Defaults to `false`.
        /// </summary>
        [Output("useUsgAcctServer")]
        public Output<bool?> UseUsgAcctServer { get; private set; } = null!;

        /// <summary>
        /// Specifies whether to use usg as a RADIUS authentication server. Defaults to `false`.
        /// </summary>
        [Output("useUsgAuthServer")]
        public Output<bool?> UseUsgAuthServer { get; private set; } = null!;

        /// <summary>
        /// Specifies whether to use vlan on wired connections. Defaults to `false`.
        /// </summary>
        [Output("vlanEnabled")]
        public Output<bool?> VlanEnabled { get; private set; } = null!;

        /// <summary>
        /// Specifies whether to use vlan on wireless connections. Must be one of `disabled`, `optional`, or `required`. Defaults to ``.
        /// </summary>
        [Output("vlanWlanMode")]
        public Output<string?> VlanWlanMode { get; private set; } = null!;


        /// <summary>
        /// Create a RadiusProfile resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RadiusProfile(string name, RadiusProfileArgs? args = null, CustomResourceOptions? options = null)
            : base("unifi:index/radiusProfile:RadiusProfile", name, args ?? new RadiusProfileArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RadiusProfile(string name, Input<string> id, RadiusProfileState? state = null, CustomResourceOptions? options = null)
            : base("unifi:index/radiusProfile:RadiusProfile", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RadiusProfile resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RadiusProfile Get(string name, Input<string> id, RadiusProfileState? state = null, CustomResourceOptions? options = null)
        {
            return new RadiusProfile(name, id, state, options);
        }
    }

    public sealed class RadiusProfileArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies whether to use RADIUS accounting. Defaults to `false`.
        /// </summary>
        [Input("accountingEnabled")]
        public Input<bool>? AccountingEnabled { get; set; }

        [Input("acctServers")]
        private InputList<Inputs.RadiusProfileAcctServerArgs>? _acctServers;

        /// <summary>
        /// RADIUS accounting servers.
        /// </summary>
        public InputList<Inputs.RadiusProfileAcctServerArgs> AcctServers
        {
            get => _acctServers ?? (_acctServers = new InputList<Inputs.RadiusProfileAcctServerArgs>());
            set => _acctServers = value;
        }

        [Input("authServers")]
        private InputList<Inputs.RadiusProfileAuthServerArgs>? _authServers;

        /// <summary>
        /// RADIUS authentication servers.
        /// </summary>
        public InputList<Inputs.RadiusProfileAuthServerArgs> AuthServers
        {
            get => _authServers ?? (_authServers = new InputList<Inputs.RadiusProfileAuthServerArgs>());
            set => _authServers = value;
        }

        /// <summary>
        /// Specifies whether to use interim_update. Defaults to `false`.
        /// </summary>
        [Input("interimUpdateEnabled")]
        public Input<bool>? InterimUpdateEnabled { get; set; }

        /// <summary>
        /// Specifies interim_update interval. Defaults to `3600`.
        /// </summary>
        [Input("interimUpdateInterval")]
        public Input<int>? InterimUpdateInterval { get; set; }

        /// <summary>
        /// The name of the profile.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The name of the site to associate the settings with.
        /// </summary>
        [Input("site")]
        public Input<string>? Site { get; set; }

        /// <summary>
        /// Specifies whether to use usg as a RADIUS accounting server. Defaults to `false`.
        /// </summary>
        [Input("useUsgAcctServer")]
        public Input<bool>? UseUsgAcctServer { get; set; }

        /// <summary>
        /// Specifies whether to use usg as a RADIUS authentication server. Defaults to `false`.
        /// </summary>
        [Input("useUsgAuthServer")]
        public Input<bool>? UseUsgAuthServer { get; set; }

        /// <summary>
        /// Specifies whether to use vlan on wired connections. Defaults to `false`.
        /// </summary>
        [Input("vlanEnabled")]
        public Input<bool>? VlanEnabled { get; set; }

        /// <summary>
        /// Specifies whether to use vlan on wireless connections. Must be one of `disabled`, `optional`, or `required`. Defaults to ``.
        /// </summary>
        [Input("vlanWlanMode")]
        public Input<string>? VlanWlanMode { get; set; }

        public RadiusProfileArgs()
        {
        }
        public static new RadiusProfileArgs Empty => new RadiusProfileArgs();
    }

    public sealed class RadiusProfileState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specifies whether to use RADIUS accounting. Defaults to `false`.
        /// </summary>
        [Input("accountingEnabled")]
        public Input<bool>? AccountingEnabled { get; set; }

        [Input("acctServers")]
        private InputList<Inputs.RadiusProfileAcctServerGetArgs>? _acctServers;

        /// <summary>
        /// RADIUS accounting servers.
        /// </summary>
        public InputList<Inputs.RadiusProfileAcctServerGetArgs> AcctServers
        {
            get => _acctServers ?? (_acctServers = new InputList<Inputs.RadiusProfileAcctServerGetArgs>());
            set => _acctServers = value;
        }

        [Input("authServers")]
        private InputList<Inputs.RadiusProfileAuthServerGetArgs>? _authServers;

        /// <summary>
        /// RADIUS authentication servers.
        /// </summary>
        public InputList<Inputs.RadiusProfileAuthServerGetArgs> AuthServers
        {
            get => _authServers ?? (_authServers = new InputList<Inputs.RadiusProfileAuthServerGetArgs>());
            set => _authServers = value;
        }

        /// <summary>
        /// Specifies whether to use interim_update. Defaults to `false`.
        /// </summary>
        [Input("interimUpdateEnabled")]
        public Input<bool>? InterimUpdateEnabled { get; set; }

        /// <summary>
        /// Specifies interim_update interval. Defaults to `3600`.
        /// </summary>
        [Input("interimUpdateInterval")]
        public Input<int>? InterimUpdateInterval { get; set; }

        /// <summary>
        /// The name of the profile.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The name of the site to associate the settings with.
        /// </summary>
        [Input("site")]
        public Input<string>? Site { get; set; }

        /// <summary>
        /// Specifies whether to use usg as a RADIUS accounting server. Defaults to `false`.
        /// </summary>
        [Input("useUsgAcctServer")]
        public Input<bool>? UseUsgAcctServer { get; set; }

        /// <summary>
        /// Specifies whether to use usg as a RADIUS authentication server. Defaults to `false`.
        /// </summary>
        [Input("useUsgAuthServer")]
        public Input<bool>? UseUsgAuthServer { get; set; }

        /// <summary>
        /// Specifies whether to use vlan on wired connections. Defaults to `false`.
        /// </summary>
        [Input("vlanEnabled")]
        public Input<bool>? VlanEnabled { get; set; }

        /// <summary>
        /// Specifies whether to use vlan on wireless connections. Must be one of `disabled`, `optional`, or `required`. Defaults to ``.
        /// </summary>
        [Input("vlanWlanMode")]
        public Input<string>? VlanWlanMode { get; set; }

        public RadiusProfileState()
        {
        }
        public static new RadiusProfileState Empty => new RadiusProfileState();
    }
}
