// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Unifi
{
    /// <summary>
    /// `unifi.SettingMgmt` manages settings for a unifi site.
    /// </summary>
    [UnifiResourceType("unifi:index/settingMgmt:SettingMgmt")]
    public partial class SettingMgmt : Pulumi.CustomResource
    {
        /// <summary>
        /// Automatically upgrade device firmware.
        /// </summary>
        [Output("autoUpgrade")]
        public Output<bool?> AutoUpgrade { get; private set; } = null!;

        /// <summary>
        /// The name of the site to associate the settings with.
        /// </summary>
        [Output("site")]
        public Output<string> Site { get; private set; } = null!;

        /// <summary>
        /// Enable SSH authentication.
        /// </summary>
        [Output("sshEnabled")]
        public Output<bool?> SshEnabled { get; private set; } = null!;

        /// <summary>
        /// SSH key.
        /// </summary>
        [Output("sshKeys")]
        public Output<ImmutableArray<Outputs.SettingMgmtSshKey>> SshKeys { get; private set; } = null!;


        /// <summary>
        /// Create a SettingMgmt resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SettingMgmt(string name, SettingMgmtArgs? args = null, CustomResourceOptions? options = null)
            : base("unifi:index/settingMgmt:SettingMgmt", name, args ?? new SettingMgmtArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SettingMgmt(string name, Input<string> id, SettingMgmtState? state = null, CustomResourceOptions? options = null)
            : base("unifi:index/settingMgmt:SettingMgmt", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SettingMgmt resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SettingMgmt Get(string name, Input<string> id, SettingMgmtState? state = null, CustomResourceOptions? options = null)
        {
            return new SettingMgmt(name, id, state, options);
        }
    }

    public sealed class SettingMgmtArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Automatically upgrade device firmware.
        /// </summary>
        [Input("autoUpgrade")]
        public Input<bool>? AutoUpgrade { get; set; }

        /// <summary>
        /// The name of the site to associate the settings with.
        /// </summary>
        [Input("site")]
        public Input<string>? Site { get; set; }

        /// <summary>
        /// Enable SSH authentication.
        /// </summary>
        [Input("sshEnabled")]
        public Input<bool>? SshEnabled { get; set; }

        [Input("sshKeys")]
        private InputList<Inputs.SettingMgmtSshKeyArgs>? _sshKeys;

        /// <summary>
        /// SSH key.
        /// </summary>
        public InputList<Inputs.SettingMgmtSshKeyArgs> SshKeys
        {
            get => _sshKeys ?? (_sshKeys = new InputList<Inputs.SettingMgmtSshKeyArgs>());
            set => _sshKeys = value;
        }

        public SettingMgmtArgs()
        {
        }
    }

    public sealed class SettingMgmtState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Automatically upgrade device firmware.
        /// </summary>
        [Input("autoUpgrade")]
        public Input<bool>? AutoUpgrade { get; set; }

        /// <summary>
        /// The name of the site to associate the settings with.
        /// </summary>
        [Input("site")]
        public Input<string>? Site { get; set; }

        /// <summary>
        /// Enable SSH authentication.
        /// </summary>
        [Input("sshEnabled")]
        public Input<bool>? SshEnabled { get; set; }

        [Input("sshKeys")]
        private InputList<Inputs.SettingMgmtSshKeyGetArgs>? _sshKeys;

        /// <summary>
        /// SSH key.
        /// </summary>
        public InputList<Inputs.SettingMgmtSshKeyGetArgs> SshKeys
        {
            get => _sshKeys ?? (_sshKeys = new InputList<Inputs.SettingMgmtSshKeyGetArgs>());
            set => _sshKeys = value;
        }

        public SettingMgmtState()
        {
        }
    }
}
