// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Unifi.Setting
{
    /// <summary>
    /// Manages Teleport settings for a UniFi site. Teleport is a secure remote access technology that allows authorized users to connect to UniFi devices from anywhere.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Unifi = Pulumiverse.Unifi;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Unifi.Setting.Teleport("example", new()
    ///     {
    ///         Enabled = true,
    ///         Subnet = "192.168.100.0/24",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [UnifiResourceType("unifi:setting/teleport:Teleport")]
    public partial class Teleport : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether Teleport is enabled.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        /// </summary>
        [Output("site")]
        public Output<string> Site { get; private set; } = null!;

        /// <summary>
        /// The subnet CIDR for Teleport (e.g., `192.168.1.0/24`). Can be empty but must be set explicitly.
        /// </summary>
        [Output("subnet")]
        public Output<string> Subnet { get; private set; } = null!;


        /// <summary>
        /// Create a Teleport resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Teleport(string name, TeleportArgs args, CustomResourceOptions? options = null)
            : base("unifi:setting/teleport:Teleport", name, args ?? new TeleportArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Teleport(string name, Input<string> id, TeleportState? state = null, CustomResourceOptions? options = null)
            : base("unifi:setting/teleport:Teleport", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Teleport resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Teleport Get(string name, Input<string> id, TeleportState? state = null, CustomResourceOptions? options = null)
        {
            return new Teleport(name, id, state, options);
        }
    }

    public sealed class TeleportArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether Teleport is enabled.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        /// </summary>
        [Input("site")]
        public Input<string>? Site { get; set; }

        /// <summary>
        /// The subnet CIDR for Teleport (e.g., `192.168.1.0/24`). Can be empty but must be set explicitly.
        /// </summary>
        [Input("subnet")]
        public Input<string>? Subnet { get; set; }

        public TeleportArgs()
        {
        }
        public static new TeleportArgs Empty => new TeleportArgs();
    }

    public sealed class TeleportState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether Teleport is enabled.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
        /// </summary>
        [Input("site")]
        public Input<string>? Site { get; set; }

        /// <summary>
        /// The subnet CIDR for Teleport (e.g., `192.168.1.0/24`). Can be empty but must be set explicitly.
        /// </summary>
        [Input("subnet")]
        public Input<string>? Subnet { get; set; }

        public TeleportState()
        {
        }
        public static new TeleportState Empty => new TeleportState();
    }
}
