// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unifi

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unifi/sdk/go/unifi/internal"
)

// The `Account` resource manages RADIUS user accounts in the UniFi controller's built-in RADIUS server.
//
// This resource is used for:
//   - WPA2/WPA3-Enterprise wireless authentication
//   - 802.1X wired authentication
//   - MAC-based device authentication
//   - VLAN assignment through RADIUS attributes
//
// Important Notes:
// 1. For MAC-based authentication:
//   - Use the device's MAC address as both username and password
//   - Convert MAC address to uppercase with no separators (e.g., '00:11:22:33:44:55' becomes '001122334455')
//
// 2. VLAN Assignment:
//   - If no VLAN is specified in the profile, clients will use the network's untagged VLAN
//   - VLAN assignment uses standard RADIUS tunnel attributes
//
// Limitations:
//   - MAC-based authentication works only for wireless and wired clients
//   - L2TP remote access VPN is not supported with MAC authentication
//   - Accounts must be unique within a site
type Account struct {
	pulumi.CustomResourceState

	// The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
	Name pulumi.StringOutput `pulumi:"name"`
	// The ID of the network (VLAN) to assign to clients authenticating with this account. This is used in conjunction with the tunnel attributes to provide VLAN assignment via RADIUS.
	NetworkId pulumi.StringPtrOutput `pulumi:"networkId"`
	// The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
	Password pulumi.StringOutput `pulumi:"password"`
	// The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
	Site pulumi.StringOutput `pulumi:"site"`
	// The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
	//   * `6` - 802 (includes Ethernet, Token Ring, FDDI) (default)
	//   * `1` - IPv4
	//   * `2` - IPv6
	//
	// Only change this if you need specific tunneling behavior.
	TunnelMediumType pulumi.IntPtrOutput `pulumi:"tunnelMediumType"`
	// The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
	//   * `13` - VLAN (default)
	//   * `1` - Point-to-Point Protocol (PPTP)
	//   * `9` - Point-to-Point Protocol (L2TP)
	//
	// Only change this if you need specific tunneling behavior.
	TunnelType pulumi.IntPtrOutput `pulumi:"tunnelType"`
}

// NewAccount registers a new resource with the given unique name, arguments, and options.
func NewAccount(ctx *pulumi.Context,
	name string, args *AccountArgs, opts ...pulumi.ResourceOption) (*Account, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Password == nil {
		return nil, errors.New("invalid value for required argument 'Password'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Account
	err := ctx.RegisterResource("unifi:index/account:Account", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAccount gets an existing Account resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAccount(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AccountState, opts ...pulumi.ResourceOption) (*Account, error) {
	var resource Account
	err := ctx.ReadResource("unifi:index/account:Account", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Account resources.
type accountState struct {
	// The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
	Name *string `pulumi:"name"`
	// The ID of the network (VLAN) to assign to clients authenticating with this account. This is used in conjunction with the tunnel attributes to provide VLAN assignment via RADIUS.
	NetworkId *string `pulumi:"networkId"`
	// The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
	Password *string `pulumi:"password"`
	// The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
	Site *string `pulumi:"site"`
	// The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
	//   * `6` - 802 (includes Ethernet, Token Ring, FDDI) (default)
	//   * `1` - IPv4
	//   * `2` - IPv6
	//
	// Only change this if you need specific tunneling behavior.
	TunnelMediumType *int `pulumi:"tunnelMediumType"`
	// The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
	//   * `13` - VLAN (default)
	//   * `1` - Point-to-Point Protocol (PPTP)
	//   * `9` - Point-to-Point Protocol (L2TP)
	//
	// Only change this if you need specific tunneling behavior.
	TunnelType *int `pulumi:"tunnelType"`
}

type AccountState struct {
	// The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
	Name pulumi.StringPtrInput
	// The ID of the network (VLAN) to assign to clients authenticating with this account. This is used in conjunction with the tunnel attributes to provide VLAN assignment via RADIUS.
	NetworkId pulumi.StringPtrInput
	// The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
	Password pulumi.StringPtrInput
	// The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
	Site pulumi.StringPtrInput
	// The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
	//   * `6` - 802 (includes Ethernet, Token Ring, FDDI) (default)
	//   * `1` - IPv4
	//   * `2` - IPv6
	//
	// Only change this if you need specific tunneling behavior.
	TunnelMediumType pulumi.IntPtrInput
	// The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
	//   * `13` - VLAN (default)
	//   * `1` - Point-to-Point Protocol (PPTP)
	//   * `9` - Point-to-Point Protocol (L2TP)
	//
	// Only change this if you need specific tunneling behavior.
	TunnelType pulumi.IntPtrInput
}

func (AccountState) ElementType() reflect.Type {
	return reflect.TypeOf((*accountState)(nil)).Elem()
}

type accountArgs struct {
	// The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
	Name *string `pulumi:"name"`
	// The ID of the network (VLAN) to assign to clients authenticating with this account. This is used in conjunction with the tunnel attributes to provide VLAN assignment via RADIUS.
	NetworkId *string `pulumi:"networkId"`
	// The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
	Password string `pulumi:"password"`
	// The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
	Site *string `pulumi:"site"`
	// The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
	//   * `6` - 802 (includes Ethernet, Token Ring, FDDI) (default)
	//   * `1` - IPv4
	//   * `2` - IPv6
	//
	// Only change this if you need specific tunneling behavior.
	TunnelMediumType *int `pulumi:"tunnelMediumType"`
	// The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
	//   * `13` - VLAN (default)
	//   * `1` - Point-to-Point Protocol (PPTP)
	//   * `9` - Point-to-Point Protocol (L2TP)
	//
	// Only change this if you need specific tunneling behavior.
	TunnelType *int `pulumi:"tunnelType"`
}

// The set of arguments for constructing a Account resource.
type AccountArgs struct {
	// The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
	Name pulumi.StringPtrInput
	// The ID of the network (VLAN) to assign to clients authenticating with this account. This is used in conjunction with the tunnel attributes to provide VLAN assignment via RADIUS.
	NetworkId pulumi.StringPtrInput
	// The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
	Password pulumi.StringInput
	// The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
	Site pulumi.StringPtrInput
	// The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
	//   * `6` - 802 (includes Ethernet, Token Ring, FDDI) (default)
	//   * `1` - IPv4
	//   * `2` - IPv6
	//
	// Only change this if you need specific tunneling behavior.
	TunnelMediumType pulumi.IntPtrInput
	// The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
	//   * `13` - VLAN (default)
	//   * `1` - Point-to-Point Protocol (PPTP)
	//   * `9` - Point-to-Point Protocol (L2TP)
	//
	// Only change this if you need specific tunneling behavior.
	TunnelType pulumi.IntPtrInput
}

func (AccountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*accountArgs)(nil)).Elem()
}

type AccountInput interface {
	pulumi.Input

	ToAccountOutput() AccountOutput
	ToAccountOutputWithContext(ctx context.Context) AccountOutput
}

func (*Account) ElementType() reflect.Type {
	return reflect.TypeOf((**Account)(nil)).Elem()
}

func (i *Account) ToAccountOutput() AccountOutput {
	return i.ToAccountOutputWithContext(context.Background())
}

func (i *Account) ToAccountOutputWithContext(ctx context.Context) AccountOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountOutput)
}

// AccountArrayInput is an input type that accepts AccountArray and AccountArrayOutput values.
// You can construct a concrete instance of `AccountArrayInput` via:
//
//	AccountArray{ AccountArgs{...} }
type AccountArrayInput interface {
	pulumi.Input

	ToAccountArrayOutput() AccountArrayOutput
	ToAccountArrayOutputWithContext(context.Context) AccountArrayOutput
}

type AccountArray []AccountInput

func (AccountArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Account)(nil)).Elem()
}

func (i AccountArray) ToAccountArrayOutput() AccountArrayOutput {
	return i.ToAccountArrayOutputWithContext(context.Background())
}

func (i AccountArray) ToAccountArrayOutputWithContext(ctx context.Context) AccountArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountArrayOutput)
}

// AccountMapInput is an input type that accepts AccountMap and AccountMapOutput values.
// You can construct a concrete instance of `AccountMapInput` via:
//
//	AccountMap{ "key": AccountArgs{...} }
type AccountMapInput interface {
	pulumi.Input

	ToAccountMapOutput() AccountMapOutput
	ToAccountMapOutputWithContext(context.Context) AccountMapOutput
}

type AccountMap map[string]AccountInput

func (AccountMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Account)(nil)).Elem()
}

func (i AccountMap) ToAccountMapOutput() AccountMapOutput {
	return i.ToAccountMapOutputWithContext(context.Background())
}

func (i AccountMap) ToAccountMapOutputWithContext(ctx context.Context) AccountMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccountMapOutput)
}

type AccountOutput struct{ *pulumi.OutputState }

func (AccountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Account)(nil)).Elem()
}

func (o AccountOutput) ToAccountOutput() AccountOutput {
	return o
}

func (o AccountOutput) ToAccountOutputWithContext(ctx context.Context) AccountOutput {
	return o
}

// The username for this RADIUS account. For regular users, this can be any unique identifier. For MAC-based authentication, this must be the device's MAC address in uppercase with no separators (e.g., '001122334455').
func (o AccountOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Account) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The ID of the network (VLAN) to assign to clients authenticating with this account. This is used in conjunction with the tunnel attributes to provide VLAN assignment via RADIUS.
func (o AccountOutput) NetworkId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Account) pulumi.StringPtrOutput { return v.NetworkId }).(pulumi.StringPtrOutput)
}

// The password for this RADIUS account. For MAC-based authentication, this must match the username (the MAC address). For regular users, this should be a secure password following your organization's password policies.
func (o AccountOutput) Password() pulumi.StringOutput {
	return o.ApplyT(func(v *Account) pulumi.StringOutput { return v.Password }).(pulumi.StringOutput)
}

// The name of the UniFi site where this RADIUS account should be created. If not specified, the default site will be used.
func (o AccountOutput) Site() pulumi.StringOutput {
	return o.ApplyT(func(v *Account) pulumi.StringOutput { return v.Site }).(pulumi.StringOutput)
}

// The RADIUS tunnel medium type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.2). Common values:
//   - `6` - 802 (includes Ethernet, Token Ring, FDDI) (default)
//   - `1` - IPv4
//   - `2` - IPv6
//
// Only change this if you need specific tunneling behavior.
func (o AccountOutput) TunnelMediumType() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Account) pulumi.IntPtrOutput { return v.TunnelMediumType }).(pulumi.IntPtrOutput)
}

// The RADIUS tunnel type attribute ([RFC 2868](https://tools.ietf.org/html/rfc2868), section 3.1). Common values:
//   - `13` - VLAN (default)
//   - `1` - Point-to-Point Protocol (PPTP)
//   - `9` - Point-to-Point Protocol (L2TP)
//
// Only change this if you need specific tunneling behavior.
func (o AccountOutput) TunnelType() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Account) pulumi.IntPtrOutput { return v.TunnelType }).(pulumi.IntPtrOutput)
}

type AccountArrayOutput struct{ *pulumi.OutputState }

func (AccountArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Account)(nil)).Elem()
}

func (o AccountArrayOutput) ToAccountArrayOutput() AccountArrayOutput {
	return o
}

func (o AccountArrayOutput) ToAccountArrayOutputWithContext(ctx context.Context) AccountArrayOutput {
	return o
}

func (o AccountArrayOutput) Index(i pulumi.IntInput) AccountOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Account {
		return vs[0].([]*Account)[vs[1].(int)]
	}).(AccountOutput)
}

type AccountMapOutput struct{ *pulumi.OutputState }

func (AccountMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Account)(nil)).Elem()
}

func (o AccountMapOutput) ToAccountMapOutput() AccountMapOutput {
	return o
}

func (o AccountMapOutput) ToAccountMapOutputWithContext(ctx context.Context) AccountMapOutput {
	return o
}

func (o AccountMapOutput) MapIndex(k pulumi.StringInput) AccountOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Account {
		return vs[0].(map[string]*Account)[vs[1].(string)]
	}).(AccountOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccountInput)(nil)).Elem(), &Account{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccountArrayInput)(nil)).Elem(), AccountArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*AccountMapInput)(nil)).Elem(), AccountMap{})
	pulumi.RegisterOutputType(AccountOutput{})
	pulumi.RegisterOutputType(AccountArrayOutput{})
	pulumi.RegisterOutputType(AccountMapOutput{})
}
