// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package unifi

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-unifi/sdk/go/unifi/internal"
)

var _ = internal.GetEnvOrDefault

type DeviceEtherLighting struct {
	// LED animation: `steady` or `breath`.
	Behavior *string `pulumi:"behavior"`
	// LED brightness, 1-100.
	Brightness *int `pulumi:"brightness"`
	// `etherlighting` (colored per-port LEDs) or `standard` (plain status LEDs).
	LedMode *string `pulumi:"ledMode"`
	// Color scheme: `network` (color by VLAN/network) or `speed` (color by link speed).
	Mode *string `pulumi:"mode"`
}

// DeviceEtherLightingInput is an input type that accepts DeviceEtherLightingArgs and DeviceEtherLightingOutput values.
// You can construct a concrete instance of `DeviceEtherLightingInput` via:
//
//	DeviceEtherLightingArgs{...}
type DeviceEtherLightingInput interface {
	pulumi.Input

	ToDeviceEtherLightingOutput() DeviceEtherLightingOutput
	ToDeviceEtherLightingOutputWithContext(context.Context) DeviceEtherLightingOutput
}

type DeviceEtherLightingArgs struct {
	// LED animation: `steady` or `breath`.
	Behavior pulumi.StringPtrInput `pulumi:"behavior"`
	// LED brightness, 1-100.
	Brightness pulumi.IntPtrInput `pulumi:"brightness"`
	// `etherlighting` (colored per-port LEDs) or `standard` (plain status LEDs).
	LedMode pulumi.StringPtrInput `pulumi:"ledMode"`
	// Color scheme: `network` (color by VLAN/network) or `speed` (color by link speed).
	Mode pulumi.StringPtrInput `pulumi:"mode"`
}

func (DeviceEtherLightingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DeviceEtherLighting)(nil)).Elem()
}

func (i DeviceEtherLightingArgs) ToDeviceEtherLightingOutput() DeviceEtherLightingOutput {
	return i.ToDeviceEtherLightingOutputWithContext(context.Background())
}

func (i DeviceEtherLightingArgs) ToDeviceEtherLightingOutputWithContext(ctx context.Context) DeviceEtherLightingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeviceEtherLightingOutput)
}

func (i DeviceEtherLightingArgs) ToDeviceEtherLightingPtrOutput() DeviceEtherLightingPtrOutput {
	return i.ToDeviceEtherLightingPtrOutputWithContext(context.Background())
}

func (i DeviceEtherLightingArgs) ToDeviceEtherLightingPtrOutputWithContext(ctx context.Context) DeviceEtherLightingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeviceEtherLightingOutput).ToDeviceEtherLightingPtrOutputWithContext(ctx)
}

// DeviceEtherLightingPtrInput is an input type that accepts DeviceEtherLightingArgs, DeviceEtherLightingPtr and DeviceEtherLightingPtrOutput values.
// You can construct a concrete instance of `DeviceEtherLightingPtrInput` via:
//
//	        DeviceEtherLightingArgs{...}
//
//	or:
//
//	        nil
type DeviceEtherLightingPtrInput interface {
	pulumi.Input

	ToDeviceEtherLightingPtrOutput() DeviceEtherLightingPtrOutput
	ToDeviceEtherLightingPtrOutputWithContext(context.Context) DeviceEtherLightingPtrOutput
}

type deviceEtherLightingPtrType DeviceEtherLightingArgs

func DeviceEtherLightingPtr(v *DeviceEtherLightingArgs) DeviceEtherLightingPtrInput {
	return (*deviceEtherLightingPtrType)(v)
}

func (*deviceEtherLightingPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**DeviceEtherLighting)(nil)).Elem()
}

func (i *deviceEtherLightingPtrType) ToDeviceEtherLightingPtrOutput() DeviceEtherLightingPtrOutput {
	return i.ToDeviceEtherLightingPtrOutputWithContext(context.Background())
}

func (i *deviceEtherLightingPtrType) ToDeviceEtherLightingPtrOutputWithContext(ctx context.Context) DeviceEtherLightingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeviceEtherLightingPtrOutput)
}

type DeviceEtherLightingOutput struct{ *pulumi.OutputState }

func (DeviceEtherLightingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DeviceEtherLighting)(nil)).Elem()
}

func (o DeviceEtherLightingOutput) ToDeviceEtherLightingOutput() DeviceEtherLightingOutput {
	return o
}

func (o DeviceEtherLightingOutput) ToDeviceEtherLightingOutputWithContext(ctx context.Context) DeviceEtherLightingOutput {
	return o
}

func (o DeviceEtherLightingOutput) ToDeviceEtherLightingPtrOutput() DeviceEtherLightingPtrOutput {
	return o.ToDeviceEtherLightingPtrOutputWithContext(context.Background())
}

func (o DeviceEtherLightingOutput) ToDeviceEtherLightingPtrOutputWithContext(ctx context.Context) DeviceEtherLightingPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v DeviceEtherLighting) *DeviceEtherLighting {
		return &v
	}).(DeviceEtherLightingPtrOutput)
}

// LED animation: `steady` or `breath`.
func (o DeviceEtherLightingOutput) Behavior() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DeviceEtherLighting) *string { return v.Behavior }).(pulumi.StringPtrOutput)
}

// LED brightness, 1-100.
func (o DeviceEtherLightingOutput) Brightness() pulumi.IntPtrOutput {
	return o.ApplyT(func(v DeviceEtherLighting) *int { return v.Brightness }).(pulumi.IntPtrOutput)
}

// `etherlighting` (colored per-port LEDs) or `standard` (plain status LEDs).
func (o DeviceEtherLightingOutput) LedMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DeviceEtherLighting) *string { return v.LedMode }).(pulumi.StringPtrOutput)
}

// Color scheme: `network` (color by VLAN/network) or `speed` (color by link speed).
func (o DeviceEtherLightingOutput) Mode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DeviceEtherLighting) *string { return v.Mode }).(pulumi.StringPtrOutput)
}

type DeviceEtherLightingPtrOutput struct{ *pulumi.OutputState }

func (DeviceEtherLightingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DeviceEtherLighting)(nil)).Elem()
}

func (o DeviceEtherLightingPtrOutput) ToDeviceEtherLightingPtrOutput() DeviceEtherLightingPtrOutput {
	return o
}

func (o DeviceEtherLightingPtrOutput) ToDeviceEtherLightingPtrOutputWithContext(ctx context.Context) DeviceEtherLightingPtrOutput {
	return o
}

func (o DeviceEtherLightingPtrOutput) Elem() DeviceEtherLightingOutput {
	return o.ApplyT(func(v *DeviceEtherLighting) DeviceEtherLighting {
		if v != nil {
			return *v
		}
		var ret DeviceEtherLighting
		return ret
	}).(DeviceEtherLightingOutput)
}

// LED animation: `steady` or `breath`.
func (o DeviceEtherLightingPtrOutput) Behavior() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DeviceEtherLighting) *string {
		if v == nil {
			return nil
		}
		return v.Behavior
	}).(pulumi.StringPtrOutput)
}

// LED brightness, 1-100.
func (o DeviceEtherLightingPtrOutput) Brightness() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DeviceEtherLighting) *int {
		if v == nil {
			return nil
		}
		return v.Brightness
	}).(pulumi.IntPtrOutput)
}

// `etherlighting` (colored per-port LEDs) or `standard` (plain status LEDs).
func (o DeviceEtherLightingPtrOutput) LedMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DeviceEtherLighting) *string {
		if v == nil {
			return nil
		}
		return v.LedMode
	}).(pulumi.StringPtrOutput)
}

// Color scheme: `network` (color by VLAN/network) or `speed` (color by link speed).
func (o DeviceEtherLightingPtrOutput) Mode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DeviceEtherLighting) *string {
		if v == nil {
			return nil
		}
		return v.Mode
	}).(pulumi.StringPtrOutput)
}

type DevicePortOverride struct {
	// The number of ports to include in a link aggregation group (LAG). Valid range: 2-8 ports. Used when:
	// * Creating switch-to-switch uplinks for increased bandwidth
	// * Setting up high-availability connections
	// * Connecting to servers requiring more bandwidth
	//   Note: All ports in the LAG must be sequential and have matching configurations.
	AggregateNumPorts *int `pulumi:"aggregateNumPorts"`
	// Set of network IDs to exclude when `forward = "customize"`. Tagged traffic on the port is *all* networks minus the ones listed here, so an empty set means "trunk everything". Computed when not set, so the controller's current exclusions are preserved without producing a diff.
	ExcludedNetworkIds []string `pulumi:"excludedNetworkIds"`
	// VLAN forwarding mode for the port. Valid values are:
	//   * `all` - Forward all VLANs (trunk port)
	//   * `native` - Only forward untagged traffic (access port)
	//   * `customize` - Forward selected VLANs (use with `excludedNetworkIds`)
	//   * `disabled` - Disable VLAN forwarding
	//
	// This attribute has NO default: leaving it unset keeps the port's existing forwarding behavior (the value is computed from the controller). Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another value instead.
	Forward *string `pulumi:"forward"`
	// A friendly name for the port that will be displayed in the UniFi controller UI. Examples:
	//   * 'Uplink to Core Switch'
	//   * 'Conference Room AP'
	//   * 'Server LACP Group 1'
	//   * 'VoIP Phone Port'
	Name *string `pulumi:"name"`
	// The ID of the network to use as the native (untagged) network on this port. This is typically used for:
	// * Access ports where devices need untagged access
	// * Trunk ports to specify the native VLAN
	// * Management networks for network devices
	//
	// Computed when not set, so the controller's current value (which it may auto-populate on a port) is preserved without producing a diff. Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another network ID instead.
	NativeNetworkconfId *string `pulumi:"nativeNetworkconfId"`
	// The physical port number on the switch to configure.
	Number int `pulumi:"number"`
	// The operating mode of the port. Valid values are:
	//   * `switch` - Normal switching mode (default)
	//     - Standard port operation for connecting devices
	//     - Supports VLANs and all standard switching features
	//   * `mirror` - Port mirroring for traffic analysis
	//     - Copies traffic from other ports for monitoring
	//     - Useful for network troubleshooting and security
	//   * `aggregate` - Link aggregation/bonding mode
	//     - Combines multiple ports for increased bandwidth
	//     - Used for switch uplinks or high-bandwidth servers
	OpMode *string `pulumi:"opMode"`
	// The Power over Ethernet (PoE) mode for the port. Valid values are:
	// * `auto` - Automatically detect and power PoE devices (recommended)
	//   - Provides power based on device negotiation
	//   - Safest option for most PoE devices
	// * `pasv24` - Passive 24V PoE
	//   - For older UniFi devices requiring passive 24V
	//   - Use with caution to avoid damage
	// * `passthrough` - PoE passthrough mode
	//   - For daisy-chaining PoE devices
	//   - Available on select UniFi switches
	// * `off` - Disable PoE on the port
	//   - For non-PoE devices
	//   - To prevent unwanted power delivery
	PoeMode *string `pulumi:"poeMode"`
	// The ID of a pre-configured port profile to apply to this port. Port profiles define settings like VLANs, PoE, and other port-specific configurations.
	PortProfileId *string `pulumi:"portProfileId"`
	// Whether the port's settings are taken from a profile (`auto`) or set per-port (`manual`). Valid values are `auto` and `manual`. Per-port VLAN overrides (`nativeNetworkconfId`, `taggedVlanMgmt`, `forward`, `excludedNetworkIds`) generally require `settingPreference = "manual"` to persist on the controller; with `auto` the controller may revert inline overrides to profile/auto behavior. Setting this to `manual` also overrides any `portProfileId` on the same port. Computed when not set, so the value the controller attaches to the port is preserved without producing a diff.
	SettingPreference *string `pulumi:"settingPreference"`
	// VLAN tagging behavior for the port. Valid values are:
	// * `auto` - Automatically handle VLAN tags (recommended)
	// * `blockAll` - Block all VLAN tagged traffic
	// * `custom` - Custom VLAN configuration (use with `forward = "customize"` and `excludedNetworkIds`)
	//
	// Computed when not set, so the controller's current value is preserved without producing a diff. Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another value instead.
	TaggedVlanMgmt *string `pulumi:"taggedVlanMgmt"`
	// The ID of the network to use for Voice over IP (VoIP) traffic on this port, for automatic voice-VLAN assignment in conjunction with LLDP-MED.
	//
	// Computed when not set, so the controller's current value is preserved without producing a diff. Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another network ID instead.
	VoiceNetworkconfId *string `pulumi:"voiceNetworkconfId"`
}

// DevicePortOverrideInput is an input type that accepts DevicePortOverrideArgs and DevicePortOverrideOutput values.
// You can construct a concrete instance of `DevicePortOverrideInput` via:
//
//	DevicePortOverrideArgs{...}
type DevicePortOverrideInput interface {
	pulumi.Input

	ToDevicePortOverrideOutput() DevicePortOverrideOutput
	ToDevicePortOverrideOutputWithContext(context.Context) DevicePortOverrideOutput
}

type DevicePortOverrideArgs struct {
	// The number of ports to include in a link aggregation group (LAG). Valid range: 2-8 ports. Used when:
	// * Creating switch-to-switch uplinks for increased bandwidth
	// * Setting up high-availability connections
	// * Connecting to servers requiring more bandwidth
	//   Note: All ports in the LAG must be sequential and have matching configurations.
	AggregateNumPorts pulumi.IntPtrInput `pulumi:"aggregateNumPorts"`
	// Set of network IDs to exclude when `forward = "customize"`. Tagged traffic on the port is *all* networks minus the ones listed here, so an empty set means "trunk everything". Computed when not set, so the controller's current exclusions are preserved without producing a diff.
	ExcludedNetworkIds pulumi.StringArrayInput `pulumi:"excludedNetworkIds"`
	// VLAN forwarding mode for the port. Valid values are:
	//   * `all` - Forward all VLANs (trunk port)
	//   * `native` - Only forward untagged traffic (access port)
	//   * `customize` - Forward selected VLANs (use with `excludedNetworkIds`)
	//   * `disabled` - Disable VLAN forwarding
	//
	// This attribute has NO default: leaving it unset keeps the port's existing forwarding behavior (the value is computed from the controller). Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another value instead.
	Forward pulumi.StringPtrInput `pulumi:"forward"`
	// A friendly name for the port that will be displayed in the UniFi controller UI. Examples:
	//   * 'Uplink to Core Switch'
	//   * 'Conference Room AP'
	//   * 'Server LACP Group 1'
	//   * 'VoIP Phone Port'
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The ID of the network to use as the native (untagged) network on this port. This is typically used for:
	// * Access ports where devices need untagged access
	// * Trunk ports to specify the native VLAN
	// * Management networks for network devices
	//
	// Computed when not set, so the controller's current value (which it may auto-populate on a port) is preserved without producing a diff. Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another network ID instead.
	NativeNetworkconfId pulumi.StringPtrInput `pulumi:"nativeNetworkconfId"`
	// The physical port number on the switch to configure.
	Number pulumi.IntInput `pulumi:"number"`
	// The operating mode of the port. Valid values are:
	//   * `switch` - Normal switching mode (default)
	//     - Standard port operation for connecting devices
	//     - Supports VLANs and all standard switching features
	//   * `mirror` - Port mirroring for traffic analysis
	//     - Copies traffic from other ports for monitoring
	//     - Useful for network troubleshooting and security
	//   * `aggregate` - Link aggregation/bonding mode
	//     - Combines multiple ports for increased bandwidth
	//     - Used for switch uplinks or high-bandwidth servers
	OpMode pulumi.StringPtrInput `pulumi:"opMode"`
	// The Power over Ethernet (PoE) mode for the port. Valid values are:
	// * `auto` - Automatically detect and power PoE devices (recommended)
	//   - Provides power based on device negotiation
	//   - Safest option for most PoE devices
	// * `pasv24` - Passive 24V PoE
	//   - For older UniFi devices requiring passive 24V
	//   - Use with caution to avoid damage
	// * `passthrough` - PoE passthrough mode
	//   - For daisy-chaining PoE devices
	//   - Available on select UniFi switches
	// * `off` - Disable PoE on the port
	//   - For non-PoE devices
	//   - To prevent unwanted power delivery
	PoeMode pulumi.StringPtrInput `pulumi:"poeMode"`
	// The ID of a pre-configured port profile to apply to this port. Port profiles define settings like VLANs, PoE, and other port-specific configurations.
	PortProfileId pulumi.StringPtrInput `pulumi:"portProfileId"`
	// Whether the port's settings are taken from a profile (`auto`) or set per-port (`manual`). Valid values are `auto` and `manual`. Per-port VLAN overrides (`nativeNetworkconfId`, `taggedVlanMgmt`, `forward`, `excludedNetworkIds`) generally require `settingPreference = "manual"` to persist on the controller; with `auto` the controller may revert inline overrides to profile/auto behavior. Setting this to `manual` also overrides any `portProfileId` on the same port. Computed when not set, so the value the controller attaches to the port is preserved without producing a diff.
	SettingPreference pulumi.StringPtrInput `pulumi:"settingPreference"`
	// VLAN tagging behavior for the port. Valid values are:
	// * `auto` - Automatically handle VLAN tags (recommended)
	// * `blockAll` - Block all VLAN tagged traffic
	// * `custom` - Custom VLAN configuration (use with `forward = "customize"` and `excludedNetworkIds`)
	//
	// Computed when not set, so the controller's current value is preserved without producing a diff. Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another value instead.
	TaggedVlanMgmt pulumi.StringPtrInput `pulumi:"taggedVlanMgmt"`
	// The ID of the network to use for Voice over IP (VoIP) traffic on this port, for automatic voice-VLAN assignment in conjunction with LLDP-MED.
	//
	// Computed when not set, so the controller's current value is preserved without producing a diff. Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another network ID instead.
	VoiceNetworkconfId pulumi.StringPtrInput `pulumi:"voiceNetworkconfId"`
}

func (DevicePortOverrideArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DevicePortOverride)(nil)).Elem()
}

func (i DevicePortOverrideArgs) ToDevicePortOverrideOutput() DevicePortOverrideOutput {
	return i.ToDevicePortOverrideOutputWithContext(context.Background())
}

func (i DevicePortOverrideArgs) ToDevicePortOverrideOutputWithContext(ctx context.Context) DevicePortOverrideOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DevicePortOverrideOutput)
}

// DevicePortOverrideArrayInput is an input type that accepts DevicePortOverrideArray and DevicePortOverrideArrayOutput values.
// You can construct a concrete instance of `DevicePortOverrideArrayInput` via:
//
//	DevicePortOverrideArray{ DevicePortOverrideArgs{...} }
type DevicePortOverrideArrayInput interface {
	pulumi.Input

	ToDevicePortOverrideArrayOutput() DevicePortOverrideArrayOutput
	ToDevicePortOverrideArrayOutputWithContext(context.Context) DevicePortOverrideArrayOutput
}

type DevicePortOverrideArray []DevicePortOverrideInput

func (DevicePortOverrideArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DevicePortOverride)(nil)).Elem()
}

func (i DevicePortOverrideArray) ToDevicePortOverrideArrayOutput() DevicePortOverrideArrayOutput {
	return i.ToDevicePortOverrideArrayOutputWithContext(context.Background())
}

func (i DevicePortOverrideArray) ToDevicePortOverrideArrayOutputWithContext(ctx context.Context) DevicePortOverrideArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DevicePortOverrideArrayOutput)
}

type DevicePortOverrideOutput struct{ *pulumi.OutputState }

func (DevicePortOverrideOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DevicePortOverride)(nil)).Elem()
}

func (o DevicePortOverrideOutput) ToDevicePortOverrideOutput() DevicePortOverrideOutput {
	return o
}

func (o DevicePortOverrideOutput) ToDevicePortOverrideOutputWithContext(ctx context.Context) DevicePortOverrideOutput {
	return o
}

// The number of ports to include in a link aggregation group (LAG). Valid range: 2-8 ports. Used when:
//   - Creating switch-to-switch uplinks for increased bandwidth
//   - Setting up high-availability connections
//   - Connecting to servers requiring more bandwidth
//     Note: All ports in the LAG must be sequential and have matching configurations.
func (o DevicePortOverrideOutput) AggregateNumPorts() pulumi.IntPtrOutput {
	return o.ApplyT(func(v DevicePortOverride) *int { return v.AggregateNumPorts }).(pulumi.IntPtrOutput)
}

// Set of network IDs to exclude when `forward = "customize"`. Tagged traffic on the port is *all* networks minus the ones listed here, so an empty set means "trunk everything". Computed when not set, so the controller's current exclusions are preserved without producing a diff.
func (o DevicePortOverrideOutput) ExcludedNetworkIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v DevicePortOverride) []string { return v.ExcludedNetworkIds }).(pulumi.StringArrayOutput)
}

// VLAN forwarding mode for the port. Valid values are:
//   - `all` - Forward all VLANs (trunk port)
//   - `native` - Only forward untagged traffic (access port)
//   - `customize` - Forward selected VLANs (use with `excludedNetworkIds`)
//   - `disabled` - Disable VLAN forwarding
//
// This attribute has NO default: leaving it unset keeps the port's existing forwarding behavior (the value is computed from the controller). Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another value instead.
func (o DevicePortOverrideOutput) Forward() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DevicePortOverride) *string { return v.Forward }).(pulumi.StringPtrOutput)
}

// A friendly name for the port that will be displayed in the UniFi controller UI. Examples:
//   - 'Uplink to Core Switch'
//   - 'Conference Room AP'
//   - 'Server LACP Group 1'
//   - 'VoIP Phone Port'
func (o DevicePortOverrideOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DevicePortOverride) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// The ID of the network to use as the native (untagged) network on this port. This is typically used for:
// * Access ports where devices need untagged access
// * Trunk ports to specify the native VLAN
// * Management networks for network devices
//
// Computed when not set, so the controller's current value (which it may auto-populate on a port) is preserved without producing a diff. Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another network ID instead.
func (o DevicePortOverrideOutput) NativeNetworkconfId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DevicePortOverride) *string { return v.NativeNetworkconfId }).(pulumi.StringPtrOutput)
}

// The physical port number on the switch to configure.
func (o DevicePortOverrideOutput) Number() pulumi.IntOutput {
	return o.ApplyT(func(v DevicePortOverride) int { return v.Number }).(pulumi.IntOutput)
}

// The operating mode of the port. Valid values are:
//   - `switch` - Normal switching mode (default)
//   - Standard port operation for connecting devices
//   - Supports VLANs and all standard switching features
//   - `mirror` - Port mirroring for traffic analysis
//   - Copies traffic from other ports for monitoring
//   - Useful for network troubleshooting and security
//   - `aggregate` - Link aggregation/bonding mode
//   - Combines multiple ports for increased bandwidth
//   - Used for switch uplinks or high-bandwidth servers
func (o DevicePortOverrideOutput) OpMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DevicePortOverride) *string { return v.OpMode }).(pulumi.StringPtrOutput)
}

// The Power over Ethernet (PoE) mode for the port. Valid values are:
// * `auto` - Automatically detect and power PoE devices (recommended)
//   - Provides power based on device negotiation
//   - Safest option for most PoE devices
//
// * `pasv24` - Passive 24V PoE
//   - For older UniFi devices requiring passive 24V
//   - Use with caution to avoid damage
//
// * `passthrough` - PoE passthrough mode
//   - For daisy-chaining PoE devices
//   - Available on select UniFi switches
//
// * `off` - Disable PoE on the port
//   - For non-PoE devices
//   - To prevent unwanted power delivery
func (o DevicePortOverrideOutput) PoeMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DevicePortOverride) *string { return v.PoeMode }).(pulumi.StringPtrOutput)
}

// The ID of a pre-configured port profile to apply to this port. Port profiles define settings like VLANs, PoE, and other port-specific configurations.
func (o DevicePortOverrideOutput) PortProfileId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DevicePortOverride) *string { return v.PortProfileId }).(pulumi.StringPtrOutput)
}

// Whether the port's settings are taken from a profile (`auto`) or set per-port (`manual`). Valid values are `auto` and `manual`. Per-port VLAN overrides (`nativeNetworkconfId`, `taggedVlanMgmt`, `forward`, `excludedNetworkIds`) generally require `settingPreference = "manual"` to persist on the controller; with `auto` the controller may revert inline overrides to profile/auto behavior. Setting this to `manual` also overrides any `portProfileId` on the same port. Computed when not set, so the value the controller attaches to the port is preserved without producing a diff.
func (o DevicePortOverrideOutput) SettingPreference() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DevicePortOverride) *string { return v.SettingPreference }).(pulumi.StringPtrOutput)
}

// VLAN tagging behavior for the port. Valid values are:
// * `auto` - Automatically handle VLAN tags (recommended)
// * `blockAll` - Block all VLAN tagged traffic
// * `custom` - Custom VLAN configuration (use with `forward = "customize"` and `excludedNetworkIds`)
//
// Computed when not set, so the controller's current value is preserved without producing a diff. Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another value instead.
func (o DevicePortOverrideOutput) TaggedVlanMgmt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DevicePortOverride) *string { return v.TaggedVlanMgmt }).(pulumi.StringPtrOutput)
}

// The ID of the network to use for Voice over IP (VoIP) traffic on this port, for automatic voice-VLAN assignment in conjunction with LLDP-MED.
//
// Computed when not set, so the controller's current value is preserved without producing a diff. Note: the underlying field uses `omitempty`, so once set it cannot be cleared back to empty through Terraform — change it to another network ID instead.
func (o DevicePortOverrideOutput) VoiceNetworkconfId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DevicePortOverride) *string { return v.VoiceNetworkconfId }).(pulumi.StringPtrOutput)
}

type DevicePortOverrideArrayOutput struct{ *pulumi.OutputState }

func (DevicePortOverrideArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DevicePortOverride)(nil)).Elem()
}

func (o DevicePortOverrideArrayOutput) ToDevicePortOverrideArrayOutput() DevicePortOverrideArrayOutput {
	return o
}

func (o DevicePortOverrideArrayOutput) ToDevicePortOverrideArrayOutputWithContext(ctx context.Context) DevicePortOverrideArrayOutput {
	return o
}

func (o DevicePortOverrideArrayOutput) Index(i pulumi.IntInput) DevicePortOverrideOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DevicePortOverride {
		return vs[0].([]DevicePortOverride)[vs[1].(int)]
	}).(DevicePortOverrideOutput)
}

type DeviceRadio struct {
	// The channel for this radio (band-specific), or `auto` to let the controller choose.
	Channel *string `pulumi:"channel"`
	// Channel width in MHz for this radio (e.g. 20, 40, 80, 160, 320).
	Ht *int `pulumi:"ht"`
	// Minimum RSSI in dBm (negative) below which clients are disconnected, when `minRssiEnabled` is true.
	MinRssi *int `pulumi:"minRssi"`
	// Whether the minimum-RSSI client-disconnect threshold is enabled on this radio. Applied together with `minRssi`.
	MinRssiEnabled *bool `pulumi:"minRssiEnabled"`
	// The radio band this block configures: `ng` (2.4GHz), `na` (5GHz), or `6e` (6GHz).
	Name string `pulumi:"name"`
	// Custom transmit power in dBm, used when `txPowerMode = "custom"`; otherwise leave unset.
	TxPower *string `pulumi:"txPower"`
	// Transmit-power mode: `auto`, `low`, `medium`, `high`, `custom`, or `disabled`. `disabled` turns the radio off (e.g. to suppress an unused 2.4GHz band on an in-wall AP).
	TxPowerMode *string `pulumi:"txPowerMode"`
}

// DeviceRadioInput is an input type that accepts DeviceRadioArgs and DeviceRadioOutput values.
// You can construct a concrete instance of `DeviceRadioInput` via:
//
//	DeviceRadioArgs{...}
type DeviceRadioInput interface {
	pulumi.Input

	ToDeviceRadioOutput() DeviceRadioOutput
	ToDeviceRadioOutputWithContext(context.Context) DeviceRadioOutput
}

type DeviceRadioArgs struct {
	// The channel for this radio (band-specific), or `auto` to let the controller choose.
	Channel pulumi.StringPtrInput `pulumi:"channel"`
	// Channel width in MHz for this radio (e.g. 20, 40, 80, 160, 320).
	Ht pulumi.IntPtrInput `pulumi:"ht"`
	// Minimum RSSI in dBm (negative) below which clients are disconnected, when `minRssiEnabled` is true.
	MinRssi pulumi.IntPtrInput `pulumi:"minRssi"`
	// Whether the minimum-RSSI client-disconnect threshold is enabled on this radio. Applied together with `minRssi`.
	MinRssiEnabled pulumi.BoolPtrInput `pulumi:"minRssiEnabled"`
	// The radio band this block configures: `ng` (2.4GHz), `na` (5GHz), or `6e` (6GHz).
	Name pulumi.StringInput `pulumi:"name"`
	// Custom transmit power in dBm, used when `txPowerMode = "custom"`; otherwise leave unset.
	TxPower pulumi.StringPtrInput `pulumi:"txPower"`
	// Transmit-power mode: `auto`, `low`, `medium`, `high`, `custom`, or `disabled`. `disabled` turns the radio off (e.g. to suppress an unused 2.4GHz band on an in-wall AP).
	TxPowerMode pulumi.StringPtrInput `pulumi:"txPowerMode"`
}

func (DeviceRadioArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*DeviceRadio)(nil)).Elem()
}

func (i DeviceRadioArgs) ToDeviceRadioOutput() DeviceRadioOutput {
	return i.ToDeviceRadioOutputWithContext(context.Background())
}

func (i DeviceRadioArgs) ToDeviceRadioOutputWithContext(ctx context.Context) DeviceRadioOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeviceRadioOutput)
}

// DeviceRadioArrayInput is an input type that accepts DeviceRadioArray and DeviceRadioArrayOutput values.
// You can construct a concrete instance of `DeviceRadioArrayInput` via:
//
//	DeviceRadioArray{ DeviceRadioArgs{...} }
type DeviceRadioArrayInput interface {
	pulumi.Input

	ToDeviceRadioArrayOutput() DeviceRadioArrayOutput
	ToDeviceRadioArrayOutputWithContext(context.Context) DeviceRadioArrayOutput
}

type DeviceRadioArray []DeviceRadioInput

func (DeviceRadioArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DeviceRadio)(nil)).Elem()
}

func (i DeviceRadioArray) ToDeviceRadioArrayOutput() DeviceRadioArrayOutput {
	return i.ToDeviceRadioArrayOutputWithContext(context.Background())
}

func (i DeviceRadioArray) ToDeviceRadioArrayOutputWithContext(ctx context.Context) DeviceRadioArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeviceRadioArrayOutput)
}

type DeviceRadioOutput struct{ *pulumi.OutputState }

func (DeviceRadioOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*DeviceRadio)(nil)).Elem()
}

func (o DeviceRadioOutput) ToDeviceRadioOutput() DeviceRadioOutput {
	return o
}

func (o DeviceRadioOutput) ToDeviceRadioOutputWithContext(ctx context.Context) DeviceRadioOutput {
	return o
}

// The channel for this radio (band-specific), or `auto` to let the controller choose.
func (o DeviceRadioOutput) Channel() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DeviceRadio) *string { return v.Channel }).(pulumi.StringPtrOutput)
}

// Channel width in MHz for this radio (e.g. 20, 40, 80, 160, 320).
func (o DeviceRadioOutput) Ht() pulumi.IntPtrOutput {
	return o.ApplyT(func(v DeviceRadio) *int { return v.Ht }).(pulumi.IntPtrOutput)
}

// Minimum RSSI in dBm (negative) below which clients are disconnected, when `minRssiEnabled` is true.
func (o DeviceRadioOutput) MinRssi() pulumi.IntPtrOutput {
	return o.ApplyT(func(v DeviceRadio) *int { return v.MinRssi }).(pulumi.IntPtrOutput)
}

// Whether the minimum-RSSI client-disconnect threshold is enabled on this radio. Applied together with `minRssi`.
func (o DeviceRadioOutput) MinRssiEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v DeviceRadio) *bool { return v.MinRssiEnabled }).(pulumi.BoolPtrOutput)
}

// The radio band this block configures: `ng` (2.4GHz), `na` (5GHz), or `6e` (6GHz).
func (o DeviceRadioOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v DeviceRadio) string { return v.Name }).(pulumi.StringOutput)
}

// Custom transmit power in dBm, used when `txPowerMode = "custom"`; otherwise leave unset.
func (o DeviceRadioOutput) TxPower() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DeviceRadio) *string { return v.TxPower }).(pulumi.StringPtrOutput)
}

// Transmit-power mode: `auto`, `low`, `medium`, `high`, `custom`, or `disabled`. `disabled` turns the radio off (e.g. to suppress an unused 2.4GHz band on an in-wall AP).
func (o DeviceRadioOutput) TxPowerMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v DeviceRadio) *string { return v.TxPowerMode }).(pulumi.StringPtrOutput)
}

type DeviceRadioArrayOutput struct{ *pulumi.OutputState }

func (DeviceRadioArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]DeviceRadio)(nil)).Elem()
}

func (o DeviceRadioArrayOutput) ToDeviceRadioArrayOutput() DeviceRadioArrayOutput {
	return o
}

func (o DeviceRadioArrayOutput) ToDeviceRadioArrayOutputWithContext(ctx context.Context) DeviceRadioArrayOutput {
	return o
}

func (o DeviceRadioArrayOutput) Index(i pulumi.IntInput) DeviceRadioOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) DeviceRadio {
		return vs[0].([]DeviceRadio)[vs[1].(int)]
	}).(DeviceRadioOutput)
}

type RadiusProfileAcctServer struct {
	// The IPv4 address of the RADIUS accounting server (e.g., '192.168.1.100'). Must be reachable from your UniFi network.
	Ip string `pulumi:"ip"`
	// The UDP port number where the RADIUS accounting service is listening. The standard port is 1813, but this can be changed if needed to match your server configuration.
	Port *int `pulumi:"port"`
	// The shared secret key used to secure communication between the UniFi controller and the RADIUS server. This must match the secret configured on your RADIUS server.
	Xsecret string `pulumi:"xsecret"`
}

// RadiusProfileAcctServerInput is an input type that accepts RadiusProfileAcctServerArgs and RadiusProfileAcctServerOutput values.
// You can construct a concrete instance of `RadiusProfileAcctServerInput` via:
//
//	RadiusProfileAcctServerArgs{...}
type RadiusProfileAcctServerInput interface {
	pulumi.Input

	ToRadiusProfileAcctServerOutput() RadiusProfileAcctServerOutput
	ToRadiusProfileAcctServerOutputWithContext(context.Context) RadiusProfileAcctServerOutput
}

type RadiusProfileAcctServerArgs struct {
	// The IPv4 address of the RADIUS accounting server (e.g., '192.168.1.100'). Must be reachable from your UniFi network.
	Ip pulumi.StringInput `pulumi:"ip"`
	// The UDP port number where the RADIUS accounting service is listening. The standard port is 1813, but this can be changed if needed to match your server configuration.
	Port pulumi.IntPtrInput `pulumi:"port"`
	// The shared secret key used to secure communication between the UniFi controller and the RADIUS server. This must match the secret configured on your RADIUS server.
	Xsecret pulumi.StringInput `pulumi:"xsecret"`
}

func (RadiusProfileAcctServerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RadiusProfileAcctServer)(nil)).Elem()
}

func (i RadiusProfileAcctServerArgs) ToRadiusProfileAcctServerOutput() RadiusProfileAcctServerOutput {
	return i.ToRadiusProfileAcctServerOutputWithContext(context.Background())
}

func (i RadiusProfileAcctServerArgs) ToRadiusProfileAcctServerOutputWithContext(ctx context.Context) RadiusProfileAcctServerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RadiusProfileAcctServerOutput)
}

// RadiusProfileAcctServerArrayInput is an input type that accepts RadiusProfileAcctServerArray and RadiusProfileAcctServerArrayOutput values.
// You can construct a concrete instance of `RadiusProfileAcctServerArrayInput` via:
//
//	RadiusProfileAcctServerArray{ RadiusProfileAcctServerArgs{...} }
type RadiusProfileAcctServerArrayInput interface {
	pulumi.Input

	ToRadiusProfileAcctServerArrayOutput() RadiusProfileAcctServerArrayOutput
	ToRadiusProfileAcctServerArrayOutputWithContext(context.Context) RadiusProfileAcctServerArrayOutput
}

type RadiusProfileAcctServerArray []RadiusProfileAcctServerInput

func (RadiusProfileAcctServerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RadiusProfileAcctServer)(nil)).Elem()
}

func (i RadiusProfileAcctServerArray) ToRadiusProfileAcctServerArrayOutput() RadiusProfileAcctServerArrayOutput {
	return i.ToRadiusProfileAcctServerArrayOutputWithContext(context.Background())
}

func (i RadiusProfileAcctServerArray) ToRadiusProfileAcctServerArrayOutputWithContext(ctx context.Context) RadiusProfileAcctServerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RadiusProfileAcctServerArrayOutput)
}

type RadiusProfileAcctServerOutput struct{ *pulumi.OutputState }

func (RadiusProfileAcctServerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RadiusProfileAcctServer)(nil)).Elem()
}

func (o RadiusProfileAcctServerOutput) ToRadiusProfileAcctServerOutput() RadiusProfileAcctServerOutput {
	return o
}

func (o RadiusProfileAcctServerOutput) ToRadiusProfileAcctServerOutputWithContext(ctx context.Context) RadiusProfileAcctServerOutput {
	return o
}

// The IPv4 address of the RADIUS accounting server (e.g., '192.168.1.100'). Must be reachable from your UniFi network.
func (o RadiusProfileAcctServerOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v RadiusProfileAcctServer) string { return v.Ip }).(pulumi.StringOutput)
}

// The UDP port number where the RADIUS accounting service is listening. The standard port is 1813, but this can be changed if needed to match your server configuration.
func (o RadiusProfileAcctServerOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v RadiusProfileAcctServer) *int { return v.Port }).(pulumi.IntPtrOutput)
}

// The shared secret key used to secure communication between the UniFi controller and the RADIUS server. This must match the secret configured on your RADIUS server.
func (o RadiusProfileAcctServerOutput) Xsecret() pulumi.StringOutput {
	return o.ApplyT(func(v RadiusProfileAcctServer) string { return v.Xsecret }).(pulumi.StringOutput)
}

type RadiusProfileAcctServerArrayOutput struct{ *pulumi.OutputState }

func (RadiusProfileAcctServerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RadiusProfileAcctServer)(nil)).Elem()
}

func (o RadiusProfileAcctServerArrayOutput) ToRadiusProfileAcctServerArrayOutput() RadiusProfileAcctServerArrayOutput {
	return o
}

func (o RadiusProfileAcctServerArrayOutput) ToRadiusProfileAcctServerArrayOutputWithContext(ctx context.Context) RadiusProfileAcctServerArrayOutput {
	return o
}

func (o RadiusProfileAcctServerArrayOutput) Index(i pulumi.IntInput) RadiusProfileAcctServerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) RadiusProfileAcctServer {
		return vs[0].([]RadiusProfileAcctServer)[vs[1].(int)]
	}).(RadiusProfileAcctServerOutput)
}

type RadiusProfileAuthServer struct {
	// The IPv4 address of the RADIUS authentication server (e.g., '192.168.1.100'). Must be reachable from your UniFi network.
	Ip string `pulumi:"ip"`
	// The UDP port number where the RADIUS authentication service is listening. The standard port is 1812, but this can be changed if needed to match your server configuration.
	Port *int `pulumi:"port"`
	// The shared secret key used to secure communication between the UniFi controller and the RADIUS server. This must match the secret configured on your RADIUS server.
	Xsecret string `pulumi:"xsecret"`
}

// RadiusProfileAuthServerInput is an input type that accepts RadiusProfileAuthServerArgs and RadiusProfileAuthServerOutput values.
// You can construct a concrete instance of `RadiusProfileAuthServerInput` via:
//
//	RadiusProfileAuthServerArgs{...}
type RadiusProfileAuthServerInput interface {
	pulumi.Input

	ToRadiusProfileAuthServerOutput() RadiusProfileAuthServerOutput
	ToRadiusProfileAuthServerOutputWithContext(context.Context) RadiusProfileAuthServerOutput
}

type RadiusProfileAuthServerArgs struct {
	// The IPv4 address of the RADIUS authentication server (e.g., '192.168.1.100'). Must be reachable from your UniFi network.
	Ip pulumi.StringInput `pulumi:"ip"`
	// The UDP port number where the RADIUS authentication service is listening. The standard port is 1812, but this can be changed if needed to match your server configuration.
	Port pulumi.IntPtrInput `pulumi:"port"`
	// The shared secret key used to secure communication between the UniFi controller and the RADIUS server. This must match the secret configured on your RADIUS server.
	Xsecret pulumi.StringInput `pulumi:"xsecret"`
}

func (RadiusProfileAuthServerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*RadiusProfileAuthServer)(nil)).Elem()
}

func (i RadiusProfileAuthServerArgs) ToRadiusProfileAuthServerOutput() RadiusProfileAuthServerOutput {
	return i.ToRadiusProfileAuthServerOutputWithContext(context.Background())
}

func (i RadiusProfileAuthServerArgs) ToRadiusProfileAuthServerOutputWithContext(ctx context.Context) RadiusProfileAuthServerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RadiusProfileAuthServerOutput)
}

// RadiusProfileAuthServerArrayInput is an input type that accepts RadiusProfileAuthServerArray and RadiusProfileAuthServerArrayOutput values.
// You can construct a concrete instance of `RadiusProfileAuthServerArrayInput` via:
//
//	RadiusProfileAuthServerArray{ RadiusProfileAuthServerArgs{...} }
type RadiusProfileAuthServerArrayInput interface {
	pulumi.Input

	ToRadiusProfileAuthServerArrayOutput() RadiusProfileAuthServerArrayOutput
	ToRadiusProfileAuthServerArrayOutputWithContext(context.Context) RadiusProfileAuthServerArrayOutput
}

type RadiusProfileAuthServerArray []RadiusProfileAuthServerInput

func (RadiusProfileAuthServerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RadiusProfileAuthServer)(nil)).Elem()
}

func (i RadiusProfileAuthServerArray) ToRadiusProfileAuthServerArrayOutput() RadiusProfileAuthServerArrayOutput {
	return i.ToRadiusProfileAuthServerArrayOutputWithContext(context.Background())
}

func (i RadiusProfileAuthServerArray) ToRadiusProfileAuthServerArrayOutputWithContext(ctx context.Context) RadiusProfileAuthServerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RadiusProfileAuthServerArrayOutput)
}

type RadiusProfileAuthServerOutput struct{ *pulumi.OutputState }

func (RadiusProfileAuthServerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*RadiusProfileAuthServer)(nil)).Elem()
}

func (o RadiusProfileAuthServerOutput) ToRadiusProfileAuthServerOutput() RadiusProfileAuthServerOutput {
	return o
}

func (o RadiusProfileAuthServerOutput) ToRadiusProfileAuthServerOutputWithContext(ctx context.Context) RadiusProfileAuthServerOutput {
	return o
}

// The IPv4 address of the RADIUS authentication server (e.g., '192.168.1.100'). Must be reachable from your UniFi network.
func (o RadiusProfileAuthServerOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v RadiusProfileAuthServer) string { return v.Ip }).(pulumi.StringOutput)
}

// The UDP port number where the RADIUS authentication service is listening. The standard port is 1812, but this can be changed if needed to match your server configuration.
func (o RadiusProfileAuthServerOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v RadiusProfileAuthServer) *int { return v.Port }).(pulumi.IntPtrOutput)
}

// The shared secret key used to secure communication between the UniFi controller and the RADIUS server. This must match the secret configured on your RADIUS server.
func (o RadiusProfileAuthServerOutput) Xsecret() pulumi.StringOutput {
	return o.ApplyT(func(v RadiusProfileAuthServer) string { return v.Xsecret }).(pulumi.StringOutput)
}

type RadiusProfileAuthServerArrayOutput struct{ *pulumi.OutputState }

func (RadiusProfileAuthServerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]RadiusProfileAuthServer)(nil)).Elem()
}

func (o RadiusProfileAuthServerArrayOutput) ToRadiusProfileAuthServerArrayOutput() RadiusProfileAuthServerArrayOutput {
	return o
}

func (o RadiusProfileAuthServerArrayOutput) ToRadiusProfileAuthServerArrayOutputWithContext(ctx context.Context) RadiusProfileAuthServerArrayOutput {
	return o
}

func (o RadiusProfileAuthServerArrayOutput) Index(i pulumi.IntInput) RadiusProfileAuthServerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) RadiusProfileAuthServer {
		return vs[0].([]RadiusProfileAuthServer)[vs[1].(int)]
	}).(RadiusProfileAuthServerOutput)
}

type WlanSchedule struct {
	// Day of week. Valid values: `sun`, `mon`, `tue`, `wed`, `thu`, `fri`, `sat`.
	DayOfWeek string `pulumi:"dayOfWeek"`
	// Duration in minutes that the network should remain active.
	Duration int `pulumi:"duration"`
	// Friendly name for this schedule block (e.g., 'Business Hours', 'Weekend Access').
	Name *string `pulumi:"name"`
	// Start hour in 24-hour format (0-23).
	StartHour int `pulumi:"startHour"`
	// Start minute (0-59).
	StartMinute *int `pulumi:"startMinute"`
}

// WlanScheduleInput is an input type that accepts WlanScheduleArgs and WlanScheduleOutput values.
// You can construct a concrete instance of `WlanScheduleInput` via:
//
//	WlanScheduleArgs{...}
type WlanScheduleInput interface {
	pulumi.Input

	ToWlanScheduleOutput() WlanScheduleOutput
	ToWlanScheduleOutputWithContext(context.Context) WlanScheduleOutput
}

type WlanScheduleArgs struct {
	// Day of week. Valid values: `sun`, `mon`, `tue`, `wed`, `thu`, `fri`, `sat`.
	DayOfWeek pulumi.StringInput `pulumi:"dayOfWeek"`
	// Duration in minutes that the network should remain active.
	Duration pulumi.IntInput `pulumi:"duration"`
	// Friendly name for this schedule block (e.g., 'Business Hours', 'Weekend Access').
	Name pulumi.StringPtrInput `pulumi:"name"`
	// Start hour in 24-hour format (0-23).
	StartHour pulumi.IntInput `pulumi:"startHour"`
	// Start minute (0-59).
	StartMinute pulumi.IntPtrInput `pulumi:"startMinute"`
}

func (WlanScheduleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*WlanSchedule)(nil)).Elem()
}

func (i WlanScheduleArgs) ToWlanScheduleOutput() WlanScheduleOutput {
	return i.ToWlanScheduleOutputWithContext(context.Background())
}

func (i WlanScheduleArgs) ToWlanScheduleOutputWithContext(ctx context.Context) WlanScheduleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WlanScheduleOutput)
}

// WlanScheduleArrayInput is an input type that accepts WlanScheduleArray and WlanScheduleArrayOutput values.
// You can construct a concrete instance of `WlanScheduleArrayInput` via:
//
//	WlanScheduleArray{ WlanScheduleArgs{...} }
type WlanScheduleArrayInput interface {
	pulumi.Input

	ToWlanScheduleArrayOutput() WlanScheduleArrayOutput
	ToWlanScheduleArrayOutputWithContext(context.Context) WlanScheduleArrayOutput
}

type WlanScheduleArray []WlanScheduleInput

func (WlanScheduleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]WlanSchedule)(nil)).Elem()
}

func (i WlanScheduleArray) ToWlanScheduleArrayOutput() WlanScheduleArrayOutput {
	return i.ToWlanScheduleArrayOutputWithContext(context.Background())
}

func (i WlanScheduleArray) ToWlanScheduleArrayOutputWithContext(ctx context.Context) WlanScheduleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WlanScheduleArrayOutput)
}

type WlanScheduleOutput struct{ *pulumi.OutputState }

func (WlanScheduleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*WlanSchedule)(nil)).Elem()
}

func (o WlanScheduleOutput) ToWlanScheduleOutput() WlanScheduleOutput {
	return o
}

func (o WlanScheduleOutput) ToWlanScheduleOutputWithContext(ctx context.Context) WlanScheduleOutput {
	return o
}

// Day of week. Valid values: `sun`, `mon`, `tue`, `wed`, `thu`, `fri`, `sat`.
func (o WlanScheduleOutput) DayOfWeek() pulumi.StringOutput {
	return o.ApplyT(func(v WlanSchedule) string { return v.DayOfWeek }).(pulumi.StringOutput)
}

// Duration in minutes that the network should remain active.
func (o WlanScheduleOutput) Duration() pulumi.IntOutput {
	return o.ApplyT(func(v WlanSchedule) int { return v.Duration }).(pulumi.IntOutput)
}

// Friendly name for this schedule block (e.g., 'Business Hours', 'Weekend Access').
func (o WlanScheduleOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v WlanSchedule) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// Start hour in 24-hour format (0-23).
func (o WlanScheduleOutput) StartHour() pulumi.IntOutput {
	return o.ApplyT(func(v WlanSchedule) int { return v.StartHour }).(pulumi.IntOutput)
}

// Start minute (0-59).
func (o WlanScheduleOutput) StartMinute() pulumi.IntPtrOutput {
	return o.ApplyT(func(v WlanSchedule) *int { return v.StartMinute }).(pulumi.IntPtrOutput)
}

type WlanScheduleArrayOutput struct{ *pulumi.OutputState }

func (WlanScheduleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]WlanSchedule)(nil)).Elem()
}

func (o WlanScheduleArrayOutput) ToWlanScheduleArrayOutput() WlanScheduleArrayOutput {
	return o
}

func (o WlanScheduleArrayOutput) ToWlanScheduleArrayOutputWithContext(ctx context.Context) WlanScheduleArrayOutput {
	return o
}

func (o WlanScheduleArrayOutput) Index(i pulumi.IntInput) WlanScheduleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) WlanSchedule {
		return vs[0].([]WlanSchedule)[vs[1].(int)]
	}).(WlanScheduleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DeviceEtherLightingInput)(nil)).Elem(), DeviceEtherLightingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DeviceEtherLightingPtrInput)(nil)).Elem(), DeviceEtherLightingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DevicePortOverrideInput)(nil)).Elem(), DevicePortOverrideArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DevicePortOverrideArrayInput)(nil)).Elem(), DevicePortOverrideArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DeviceRadioInput)(nil)).Elem(), DeviceRadioArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*DeviceRadioArrayInput)(nil)).Elem(), DeviceRadioArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RadiusProfileAcctServerInput)(nil)).Elem(), RadiusProfileAcctServerArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RadiusProfileAcctServerArrayInput)(nil)).Elem(), RadiusProfileAcctServerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RadiusProfileAuthServerInput)(nil)).Elem(), RadiusProfileAuthServerArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RadiusProfileAuthServerArrayInput)(nil)).Elem(), RadiusProfileAuthServerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*WlanScheduleInput)(nil)).Elem(), WlanScheduleArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WlanScheduleArrayInput)(nil)).Elem(), WlanScheduleArray{})
	pulumi.RegisterOutputType(DeviceEtherLightingOutput{})
	pulumi.RegisterOutputType(DeviceEtherLightingPtrOutput{})
	pulumi.RegisterOutputType(DevicePortOverrideOutput{})
	pulumi.RegisterOutputType(DevicePortOverrideArrayOutput{})
	pulumi.RegisterOutputType(DeviceRadioOutput{})
	pulumi.RegisterOutputType(DeviceRadioArrayOutput{})
	pulumi.RegisterOutputType(RadiusProfileAcctServerOutput{})
	pulumi.RegisterOutputType(RadiusProfileAcctServerArrayOutput{})
	pulumi.RegisterOutputType(RadiusProfileAuthServerOutput{})
	pulumi.RegisterOutputType(RadiusProfileAuthServerArrayOutput{})
	pulumi.RegisterOutputType(WlanScheduleOutput{})
	pulumi.RegisterOutputType(WlanScheduleArrayOutput{})
}
