// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages the site Connectivity settings for a UniFi site. The `enabled` flag controls **wireless meshing** (shown as "Wireless Meshing" in the controller UI): when on, access points can uplink to the network over a hidden wireless backhaul instead of Ethernet, and each AP keeps a standby mesh radio running for failover. Disable it on a fully wired site to reclaim that radio/airtime; APs that lose their wired uplink then go offline rather than re-joining over mesh. The controller-generated mesh SSID and PSK are intentionally not managed by this resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as unifi from "@pulumiverse/unifi";
 *
 * const example = new unifi.setting.Connectivity("example", {enabled: false});
 * ```
 */
export class Connectivity extends pulumi.CustomResource {
    /**
     * Get an existing Connectivity resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConnectivityState, opts?: pulumi.CustomResourceOptions): Connectivity {
        return new Connectivity(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:setting/connectivity:Connectivity';

    /**
     * Returns true if the given object is an instance of Connectivity.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Connectivity {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Connectivity.__pulumiType;
    }

    /**
     * Whether wireless meshing is enabled for the site.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
     */
    declare public readonly site: pulumi.Output<string>;

    /**
     * Create a Connectivity resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConnectivityArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConnectivityArgs | ConnectivityState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConnectivityState | undefined;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["site"] = state?.site;
        } else {
            const args = argsOrState as ConnectivityArgs | undefined;
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["site"] = args?.site;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Connectivity.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Connectivity resources.
 */
export interface ConnectivityState {
    /**
     * Whether wireless meshing is enabled for the site.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
     */
    site?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Connectivity resource.
 */
export interface ConnectivityArgs {
    /**
     * Whether wireless meshing is enabled for the site.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * The name of the UniFi site where this resource should be applied. If not specified, the default site will be used.
     */
    site?: pulumi.Input<string | undefined>;
}
