// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./mgmt";
export * from "./usg";

// Import resources to register:
import { Mgmt } from "./mgmt";
import { USG } from "./usg";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "unifi:Setting/mgmt:Mgmt":
                return new Mgmt(name, <any>undefined, { urn })
            case "unifi:Setting/uSG:USG":
                return new USG(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("unifi", "Setting/mgmt", _module)
pulumi.runtime.registerResourceModule("unifi", "Setting/uSG", _module)
