// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * `unifi.Account` manages a RADIUS user account
 *
 * To authenticate devices based on MAC address, use the MAC address as the username and password under client creation.
 * Convert lowercase letters to uppercase, and also remove colons or periods from the MAC address.
 *
 * ATTENTION: If the user profile does not include a VLAN, the client will fall back to the untagged VLAN.
 *
 * NOTE: MAC-based authentication accounts can only be used for wireless and wired clients. L2TP remote access does not apply.
 */
export class Account extends pulumi.CustomResource {
    /**
     * Get an existing Account resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AccountState, opts?: pulumi.CustomResourceOptions): Account {
        return new Account(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'unifi:index/account:Account';

    /**
     * Returns true if the given object is an instance of Account.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Account {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Account.__pulumiType;
    }

    /**
     * The name of the account.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * ID of the network for this account
     */
    public readonly networkId!: pulumi.Output<string | undefined>;
    /**
     * The password of the account.
     */
    public readonly password!: pulumi.Output<string>;
    /**
     * The name of the site to associate the account with.
     */
    public readonly site!: pulumi.Output<string>;
    /**
     * See [RFC 2868](https://www.rfc-editor.org/rfc/rfc2868) section 3.2 Defaults to `6`.
     */
    public readonly tunnelMediumType!: pulumi.Output<number | undefined>;
    /**
     * See [RFC 2868](https://www.rfc-editor.org/rfc/rfc2868) section 3.1 Defaults to `13`.
     */
    public readonly tunnelType!: pulumi.Output<number | undefined>;

    /**
     * Create a Account resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AccountArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccountArgs | AccountState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AccountState | undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["networkId"] = state ? state.networkId : undefined;
            resourceInputs["password"] = state ? state.password : undefined;
            resourceInputs["site"] = state ? state.site : undefined;
            resourceInputs["tunnelMediumType"] = state ? state.tunnelMediumType : undefined;
            resourceInputs["tunnelType"] = state ? state.tunnelType : undefined;
        } else {
            const args = argsOrState as AccountArgs | undefined;
            if ((!args || args.password === undefined) && !opts.urn) {
                throw new Error("Missing required property 'password'");
            }
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["networkId"] = args ? args.networkId : undefined;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["site"] = args ? args.site : undefined;
            resourceInputs["tunnelMediumType"] = args ? args.tunnelMediumType : undefined;
            resourceInputs["tunnelType"] = args ? args.tunnelType : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Account.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Account resources.
 */
export interface AccountState {
    /**
     * The name of the account.
     */
    name?: pulumi.Input<string>;
    /**
     * ID of the network for this account
     */
    networkId?: pulumi.Input<string>;
    /**
     * The password of the account.
     */
    password?: pulumi.Input<string>;
    /**
     * The name of the site to associate the account with.
     */
    site?: pulumi.Input<string>;
    /**
     * See [RFC 2868](https://www.rfc-editor.org/rfc/rfc2868) section 3.2 Defaults to `6`.
     */
    tunnelMediumType?: pulumi.Input<number>;
    /**
     * See [RFC 2868](https://www.rfc-editor.org/rfc/rfc2868) section 3.1 Defaults to `13`.
     */
    tunnelType?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Account resource.
 */
export interface AccountArgs {
    /**
     * The name of the account.
     */
    name?: pulumi.Input<string>;
    /**
     * ID of the network for this account
     */
    networkId?: pulumi.Input<string>;
    /**
     * The password of the account.
     */
    password: pulumi.Input<string>;
    /**
     * The name of the site to associate the account with.
     */
    site?: pulumi.Input<string>;
    /**
     * See [RFC 2868](https://www.rfc-editor.org/rfc/rfc2868) section 3.2 Defaults to `6`.
     */
    tunnelMediumType?: pulumi.Input<number>;
    /**
     * See [RFC 2868](https://www.rfc-editor.org/rfc/rfc2868) section 3.1 Defaults to `13`.
     */
    tunnelType?: pulumi.Input<number>;
}
